# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Melle Dijkstra'
tagline: 'A place of thought'
# titleSuffix: ' · Melle Dijkstra'
email: dev.melle@gmail.com
description: 'A place of thought'
# >- # this means to ignore newlines until "baseurl:"
# Learn anything about science related topics. This is is where I share my latest ideas.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://melledijkstra.github.io" # the base hostname & protocol for your site, e.g. http://example.com
disqusId: "live-melledijkstra"

excerpt_separator: <!--more-->

permalink: /:collection/:title

# Collections
collections:
    stories:
        output: true
    projects:

defaults:
    -   scope:
            path: "" # an empty string means all files in the project
            type: "stories"
        values:
            layout: "story"
            tagline: 'A place of thought'
    -   scope:
            path: "files"
        values:
            sitemap: false
    -   scope:
            path: "sketches"
        values:
            sitemap: false

# Build settings
# theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    # - jekyll-paginate

#
#  PLUGIN CONFIGURATION
#

# - jekyll-paginate
# paginate: 30
# paginate-path: "/stories/page:num/"

# jekyll-seo-tag
webmaster_verifications:
    google: 'ofJ-CvPrDlbbef873pn7tx4OAxwtGGmaoDi-f1D2pz4'
    bing: 'A257B38ED344E8B133674B441B888037'
#    alexa: 1234
#    yandex: 1234
#    baidu: 1234

author:
    name: Melle Dijkstra
    twitter: dijkstrascience

twitter:
    username: dijkstrascience
    card: summary

logo: '/assets/images/logo.png'

social:
    name: Melle Dijkstra
    links:
        - https://twitter.com/dijkstrascience
        - https://www.linkedin.com/in/melledijkstra
        - https://github.com/melledijkstra

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
